[package]
name = "stage2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "0.6.0"
csv = "1.1.5"
serde = "1.0"
itertools = "0.10.0"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
