[package]
name = "stage2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"

[dev-dependencies]
env_logger = "*"
test-env-log = "0.2"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"
